"""Compute per-run zero offsets for Langmuir channels."""

from __future__ import annotations

import csv
import sys
from dataclasses import dataclass
from pathlib import Path

from bapsf_lapd import ChannelKind, LapdDataset


MANIFEST = Path("config/may2026_run_manifest.toml")
TOML_OUTPUT = Path("processed/trace_zero_offsets.toml")
CSV_OUTPUT = Path("processed/trace_zero_offsets.csv")
CHANNELS = (ChannelKind.ISAT, ChannelKind.I_SWEEP, ChannelKind.V_SWEEP)
TAIL_DURATION_S = 200e-6


@dataclass(frozen=True)
class OffsetRow:
    run_id: str
    experiment_set: int
    channel: str
    port: int | None
    measured_mean_v: float
    target_end_v: float
    offset_v: float
    std_v: float
    stderr_v: float
    n_shots: int
    n_samples: int
    sample_start: int
    sample_stop: int
    tail_duration_s: float


def _toml_float(value: float) -> str:
    return f"{value:.10g}"


def build_rows(dataset: LapdDataset, tail_duration_s: float = TAIL_DURATION_S) -> list[OffsetRow]:
    rows: list[OffsetRow] = []
    for run_id in dataset.run_ids():
        run = dataset.run(run_id)
        for channel in CHANNELS:
            stats = run.zero_offset_stats(channel, tail_duration_s=tail_duration_s)
            channel_config = run.config.channel(channel)
            rows.append(
                OffsetRow(
                    run_id=run_id,
                    experiment_set=run.config.experiment_set.id,
                    channel=channel.value,
                    port=channel_config.port,
                    measured_mean_v=stats.measured_mean_v,
                    target_end_v=stats.target_end_v,
                    offset_v=stats.offset_v,
                    std_v=stats.std_v,
                    stderr_v=stats.stderr_v,
                    n_shots=stats.n_shots,
                    n_samples=stats.n_samples,
                    sample_start=stats.sample_start,
                    sample_stop=stats.sample_stop,
                    tail_duration_s=stats.tail_duration_s,
                )
            )
    return rows


def write_csv(rows: list[OffsetRow], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].__dict__))
        writer.writeheader()
        for row in rows:
            writer.writerow(row.__dict__)


def write_toml(rows: list[OffsetRow], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/process_trace_zero_offsets.py",
        "[method]",
        'description = "Offsets are SIS-converted voltage offsets before multiplicative calibration. Current channels target zero at the trace end. V_sweep targets voltage_start / multiplier, so the calibrated tail lands on the low side of the programmed ramp."',
        f"tail_duration_requested_s = {_toml_float(TAIL_DURATION_S)}",
        "",
    ]
    for row in rows:
        lines.extend(
            [
                f'[runs."{row.run_id}".{row.channel}]',
                f"experiment_set = {row.experiment_set}",
                f"port = {row.port}" if row.port is not None else "port = 0",
                f"measured_mean_v = {_toml_float(row.measured_mean_v)}",
                f"target_end_v = {_toml_float(row.target_end_v)}",
                f"offset_v = {_toml_float(row.offset_v)}",
                f"std_v = {_toml_float(row.std_v)}",
                f"stderr_v = {_toml_float(row.stderr_v)}",
                f"n_shots = {row.n_shots}",
                f"n_samples = {row.n_samples}",
                f"sample_start = {row.sample_start}",
                f"sample_stop = {row.sample_stop}",
                f"tail_duration_s = {_toml_float(row.tail_duration_s)}",
                "",
            ]
        )
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    dataset = LapdDataset.from_manifest(MANIFEST)
    rows = build_rows(dataset)
    write_csv(rows, CSV_OUTPUT)
    write_toml(rows, TOML_OUTPUT)
    sys.stdout.write(f"Wrote {CSV_OUTPUT}\nWrote {TOML_OUTPUT}\n")


if __name__ == "__main__":
    main()
